import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'about',
    'function-index',
    {
      type: 'category',
      label: 'Primeiros Passos',
      collapsed: false,
      items: [
        'getting-started/introduction',
        'getting-started/syntax',
        'getting-started/variables',
        'getting-started/conditionals',
        'getting-started/loops',
        'getting-started/personalization-strings',
        'getting-started/comments',
      ],
    },
    {
      type: 'category',
      label: 'Funções de String',
      items: [{ type: 'autogenerated', dirName: 'string-functions' }],
    },
    {
      type: 'category',
      label: 'Funções Matemáticas',
      items: [{ type: 'autogenerated', dirName: 'math-functions' }],
    },
    {
      type: 'category',
      label: 'Funções de Data',
      items: [{ type: 'autogenerated', dirName: 'date-functions' }],
    },
    {
      type: 'category',
      label: 'Funções Utilitárias',
      items: [{ type: 'autogenerated', dirName: 'utility-functions' }],
    },
    {
      type: 'category',
      label: 'Funções de Criptografia',
      items: [{ type: 'autogenerated', dirName: 'encryption-functions' }],
    },
    {
      type: 'category',
      label: 'Funções de Data Extension',
      items: [{ type: 'autogenerated', dirName: 'data-extension-functions' }],
    },
    {
      type: 'category',
      label: 'Funções de Conteúdo',
      items: [{ type: 'autogenerated', dirName: 'content-functions' }],
    },
    {
      type: 'category',
      label: 'Funções HTTP',
      items: [{ type: 'autogenerated', dirName: 'http-functions' }],
    },
    {
      type: 'category',
      label: 'Funções de Sites',
      items: [{ type: 'autogenerated', dirName: 'sites-functions' }],
    },
    {
      type: 'category',
      label: 'Funções Sociais',
      items: [{ type: 'autogenerated', dirName: 'social-functions' }],
    },
    {
      type: 'category',
      label: 'Funções SMS',
      items: [{ type: 'autogenerated', dirName: 'sms-functions' }],
    },
    {
      type: 'category',
      label: 'Funções de Contatos',
      items: [{ type: 'autogenerated', dirName: 'contacts-functions' }],
    },
    {
      type: 'category',
      label: 'Funções Salesforce',
      items: [{ type: 'autogenerated', dirName: 'salesforce-functions' }],
    },
    {
      type: 'category',
      label: 'Microsoft Dynamics CRM',
      items: [{ type: 'autogenerated', dirName: 'microsoft-dynamics-crm-functions' }],
    },
    {
      type: 'category',
      label: 'Funções de API',
      items: [{ type: 'autogenerated', dirName: 'api-functions' }],
    },
  ],
};

export default sidebars;