import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'foreword/index',
        'introduction/index',
        'about/index',
        'legal/index',
        'privacy/index',
      ],
    },
    {
      type: 'category',
      label: 'Language',
      collapsed: false,
      items: [
        'language/index',
        'language-syntax/index',
        'naming-convention/index',
        'execution-context/index',
        'scope/index',
        'script-blocks/index',
        'ampscript-blocks/index',
        'inline-ampscript/index',
        'tag-based-syntax/index',
        'comments/index',
        {
          type: 'category',
          label: 'Variables',
          items: [
            'variables/index',
            'declaring-variables/index',
            'setting-variables/index',
            'using-variables/index',
          ],
        },
        {
          type: 'category',
          label: 'Constants',
          items: [
            'constants/index',
            'string-constants/index',
            'numeric-constants/index',
            'boolean-constants/index',
          ],
        },
        {
          type: 'category',
          label: 'Operators',
          items: [
            'comparison-operators/index',
            'logical-operators/index',
            'not-operator/index',
            'order-of-operations/index',
          ],
        },
        'statements/index',
        'process-loops/index',
        'function-calls/index',
        'controlling-expression-evaluation/index',
        'output/index',
        'outputline/index',
      ],
    },
    {
      type: 'category',
      label: 'Functions',
      items: [
        'function-index/index',
        'functions/index',
        {
          type: 'category',
          label: 'Math',
          items: [
            'math-functions/index',
            'add/index',
            'subtract/index',
            'multiply/index',
            'divide/index',
            'mod/index',
            'random/index',
          ],
        },
        {
          type: 'category',
          label: 'String',
          items: [
            'string-functions/index',
            'char/index',
            'concat/index',
            'format/index',
            'formatcurrency/index',
            'formatnumber/index',
            'indexof/index',
            'length/index',
            'lowercase/index',
            'propercase/index',
            'regexmatch/index',
            'replace/index',
            'replacelist/index',
            'stringtodate/index',
            'stringtohex/index',
            'substring/index',
            'trim/index',
            'uppercase/index',
            'urlencode/index',
            'wraplongurl/index',
          ],
        },
        {
          type: 'category',
          label: 'Date & Time',
          items: [
            'date-and-time-functions/index',
            'dateadd/index',
            'datediff/index',
            'dateparse/index',
            'datepart/index',
            'formatdate/index',
            'getsendtime/index',
            'localdatetosystemdate/index',
            'now/index',
            'systemdatetolocaldate/index',
          ],
        },
        {
          type: 'category',
          label: 'Data Extension',
          items: [
            'data-extension-functions/index',
            'dataextensionrowcount/index',
            'deletedata/index',
            'deletede/index',
            'executefilter/index',
            'executefilterorderedrows/index',
            'insertdata/index',
            'insertde/index',
            'lookuporderedrows/index',
            'lookuporderedrowscs/index',
            'lookuprows/index',
            'lookuprowscs/index',
            'updatedata/index',
            'updatede/index',
            'upsertcontact/index',
            'upsertdata/index',
            'upsertde/index',
          ],
        },
        {
          type: 'category',
          label: 'Rowset & Data',
          items: [
            'row/index',
            'rowcount/index',
            'field/index',
            'claimrow/index',
            'claimrowvalue/index',
            'buildrowsetfromjson/index',
            'buildrowsetfromstring/index',
            'buildrowsetfromxml/index',
            'buildoptionlist/index',
          ],
        },
        {
          type: 'category',
          label: 'Content',
          items: [
            'content-functions/index',
            'contentarea/index',
            'contentareabyid/index',
            'contentareabyname/index',
            'contentblockbyid/index',
            'contentblockbykey/index',
            'contentblockbyname/index',
            'contentimagebyid/index',
            'contentimagebykey/index',
            'getportfolioitem/index',
            'image/index',
            'treatascontent/index',
            'treatascontentarea/index',
            'transformxml/index',
            'beginimpressionregion/index',
            'endimpressionregion/index',
            'ratingstars/index',
            'v/index',
          ],
        },
        {
          type: 'category',
          label: 'HTTP',
          items: [
            'http-functions/index',
            'httpget/index',
            'beforehttpget/index',
            'afterhttpget/index',
            'httpgetwrap/index',
            'httppost/index',
            'httppost2/index',
            'httppostwithretry/index',
            'httprequestheader/index',
          ],
        },
        {
          type: 'category',
          label: 'Encryption & Encoding',
          items: [
            'encryption-and-encoding-functions/index',
            'base64decode/index',
            'base64encode/index',
            'decryptsymmetric/index',
            'encryptsymmetric/index',
            'md5/index',
            'sha1/index',
            'sha256/index',
            'sha512/index',
          ],
        },
        {
          type: 'category',
          label: 'Utility',
          items: [
            'utility-functions/index',
            'attributevalue/index',
            'attributevalue-empty/index',
            'domain/index',
            'empty/index',
            'getjwt/index',
            'getjwtbykeyname/index',
            'getvalue/index',
            'guid/index',
            'iif/index',
            'ischtmlbrowser/index',
            'isemailaddress/index',
            'isnull/index',
            'isnulldefault/index',
            'isphonenumber/index',
            'longsfid/index',
            'queryparameter/index',
            'raiseerror/index',
            'redirect/index',
            'redirectto/index',
            'requestparameter/index',
            'setvalue/index',
          ],
        },
        {
          type: 'category',
          label: 'Site-Based',
          items: [
            'site-based-functions/index',
            'barcodeurl/index',
            'cloudpagesurl/index',
            'livecontentmicrositeurl/index',
            'micrositeurl/index',
            'wat/index',
            'watp/index',
          ],
        },
        {
          type: 'category',
          label: 'Marketing Cloud API',
          items: [
            'marketing-cloud-api-functions/index',
            {
              type: 'category',
              label: 'Content Model',
              items: [
                'content-model-functions/index',
                'addobjectarrayitem/index',
                'createobject/index',
                'invokecreate/index',
                'invokedelete/index',
                'invokeexecute/index',
                'invokeperform/index',
                'invokeretrieve/index',
                'invokeupdate/index',
                'setobjectproperty/index',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Sales & Service Cloud',
          items: [
            'sales-and-service-cloud-functions/index',
            'createsalesforceobject/index',
            'retrievesalesforcejobsources/index',
            'retrievesalesforceobjects/index',
            'updatesinglesalesforceobject/index',
          ],
        },
        {
          type: 'category',
          label: 'Microsoft Dynamics CRM',
          items: [
            'microsoft-dynamics-crm-functions/index',
            'addmscrmlistmember/index',
            'createmscrmrecord/index',
            'describemscrmentities/index',
            'describemscrmentityattributes/index',
            'retrievemscrmrecords/index',
            'retrievemscrmrecordsfetchxml/index',
            'setstatemscrmrecord/index',
            'updatemscrmrecords/index',
            'upsertmscrmrecord/index',
          ],
        },
        {
          type: 'category',
          label: 'MobileConnect',
          items: [
            'mobileconnect-functions/index',
            'createsmsconversation/index',
            'endsmsconversation/index',
            'setsmsconversationnextkeyword/index',
          ],
        },
        {
          type: 'category',
          label: 'Social',
          items: [
            'social-functions/index',
            'getpublishedsocialcontent/index',
            'getsocialpublishurl/index',
            'getsocialpublishurlbyname/index',
          ],
        },
        {
          type: 'category',
          label: 'Einstein',
          items: [
            'einstein-email-recommendation-functions/index',
          ],
        },
        'attachfile/index',
      ],
    },
    {
      type: 'category',
      label: 'Data Strings',
      items: [
        'attributes/index',
        'attribute-strings/index',
        {
          type: 'category',
          label: 'Personalization Strings',
          items: [
            'personalization-strings-overview/index',
            'personalization-string-syntax/index',
          ],
        },
        'system-strings/index',
        'sender-data-strings/index',
        'email-url-data-strings/index',
        'mobileconnect-contact-data-strings/index',
        'dynamic-link-tracking/index',
        {
          type: 'category',
          label: 'Authenticated Functions',
          items: [
            'authenticatedemployeeid/index',
            'authenticatedemployeenotificationaddress/index',
            'authenticatedemployeeusername/index',
            'authenticatedenterpriseid/index',
            'authenticatedmemberid/index',
            'authenticatedmembername/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Content Syndication',
      items: [
        'content-syndication/index',
        'content-syndication-overview/index',
        'content-syndication-syntax/index',
        'content-syndication-variables-and-functions/index',
        'content-syndication-empty-return-handling/index',
      ],
    },
    {
      type: 'category',
      label: 'Exclusion Scripts',
      items: [
        'exclusion-scripts/index',
        'exclusion-scripts-syntax/index',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'ampscript-and-excel/index',
        'ampscript-and-guide-template-language/index',
        'ampscript-and-guide-syntax/index',
        'ampscript-and-server-side-javascript/index',
        'ampscript-and-gtl/index',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      items: [
        'best-practices/index',
        'best-practices-coding-defensively/index',
        'best-practices-debugging/index',
        'best-practices-modularization/index',
        'best-practices-shared-content-areas/index',
        'best-practices-try-catch/index',
        'best-practices-validate/index',
        'best-practices-variable-values/index',
        'best-practices-raiseerror/index',
        'best-practices-caching/index',
        'best-practices-script-block-organization/index',
        'best-practices-attributevalue-empty/index',
        'best-practices-audience-size/index',
        'best-practices-content-syndication/index',
        'best-practices-dynamic-content-area-paths/index',
        'best-practices-occurrences/index',
      ],
    },
  ],
};

export default sidebars;